version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pdm
      - run:
          name: Run tests
          command: python -m unittest
  build-and-check-formatting:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pdm
      - run:
          name: Check formatting
          command: python -m black --check . --target-version py310
workflows:
  test:
    jobs:
      - build-and-test
  check-formatting:
    jobs:
      - build-and-check-formatting
